# Generated by Django 3.1.7 on 2021-02-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtocode',
            name='city_code',
            field=models.IntegerField(),
        ),
    ]
