# Generated by Django 3.1.7 on 2021-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rto', '0002_auto_20210220_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtocode',
            name='city_code',
            field=models.CharField(max_length=4),
        ),
    ]
